version: '3.4'

services:
  # Todo: 2.27.2 Define mongo 
  catalogdb:
    image: mongo
    
  basketdb:
    image: redis:alpine
    
  discountdb:
    image: postgres
    
  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    
  rabbitmq:
    image: rabbitmq:3-management-alpine
    
  pgadmin:
    image: dpage/pgadmin4
    
  # Todo: 3.15.1 Setup portainer 
  portainer:
    image: portainer/portainer-ce
      
  # Todo: 2.27.1 Basket Api 
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
       
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile   
      
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
      
  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
      
  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/Ocelot.ApiGateway/Dockerfile
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
#  identityserver:
#    image: ${DOCKER_REGISTRY-}identityserver
#    build:
#      context: .
#      dockerfile: Infrastructure/EShopping.Identity/Dockerfile
      
# Todo: 2.27.3 Define service volume on Docker for saving data
volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
  elasticsearch-data:  
